# This is a basic workflow to start with action

name: Build frontEnd production

# Controls when the workflow will run
on:
  # Triggers for workflow when on push or pull request events, but only for "master" branch
  push:
    branches: [main]
  pull_request:  
    branches: [main]
  
  # Allow that you run this workflow manually from the action tab
  workflow_dispatch:

# A workflow is made up of one o more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buils"
  build:
    # This runner job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of task that be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB-WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
        # Setup NodeJs
      - name: Setup nodejs
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
      
      # Install dependences
      - name: Install deps
        run: npm i --force
      
      # Build app for production
      - name: Build app bundle
        run: npm run build
      
      # Route file renaming
      - name: Rename index for routing
        run: mv dist/index.html dist/404.html 

      # Deploy to Github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      

